### ISSUE TITLE
[FEATURE] Pass commandline arguments to project editor

### ISSUE THREAD

**Issue by Myrkie** [vrchat-community/creator-companion#370] opened 2023-10-18 08:25 UTC
**Is your feature request related to a problem? Please describe.**
Without this feature its impossible to pass command line arguments to a project that has been opened through the VCC

**Describe the solution you'd like**
The unity hub allows you to pass certain arguments towards that projects editor, I would love this feature in the VCC so I can completely remove unity hub from my workflow. 

**Additional context**
an example argument to pass would be `--force-device-index INT` which lets you force which GPU the editor is rendered on which is nice when compiling shader's while in VR.

![image](https://github.com/vrchat-community/creator-companion/assets/20288698/461d8d5e-7e11-4110-9392-10d5bd74fa7b)

![image](https://github.com/vrchat-community/creator-companion/assets/20288698/5c0ea1c6-89b2-4cd0-9ab8-8df375f725a9)

![image](https://github.com/vrchat-community/creator-companion/assets/20288698/6198a7c4-6dc2-4748-8a6c-8c63c390bb82)

**Comment by Myrkie** [comment] 2023-10-18 08:26
just noticed duplicate of https://github.com/vrchat-community/creator-companion/issues/135

**Comment by orels1** [comment] 2023-10-18 20:24
I'll close this as a duplicate of #135 as you noted. This is something we still want to explore in the future

**Closed by orels1** 2023-10-18 20:24 UTC
Labels: enhancement
