### ISSUE TITLE
[BUG] Both UdonSharp and SDK 3.4.0-beta.1 is installed when installing package depends on UdonSharp to project with VRCSDK worlds 3.3.0

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#356] opened 2023-09-28 00:53 UTC
### Describe the bug

Both UdonSharp and SDK 3.4.0-beta.1 is installed when installing package depends on UdonSharp to project with VRCSDK worlds 3.3.0

### To Reproduce

**Pattern A**: Project without UdonSharp

1. Create project with VRCSDK 3.3.0
2. Install package depends on UdonSharp.
   I use KinelVideoPlayer by https://vpm.niri.la/ or QvPen by https://vpm.ureishi.net/repos.json
3. UdonSharp and VRCSDK 3.4.0-beta.1 is installed

**Pattern B**: Project with UdonSharp
1. Create project with VRCSDK 3.3.0 and UdonSharp
2. Install package depends on UdonSharp.
   I use KinelVideoPlayer by https://vpm.niri.la/ or QvPen by https://vpm.ureishi.net/repos.json
3. VRCSDK 3.4.0-beta.1 is installed and UdonSharp is not removed

### Expected behavior

**Pattern A**
UdonSharp should not be installed OR VRCSDK should not upgraded since currently installed version is compatible with packages

**Pattern B**
UdonSharp should be removed OR VRCSDK should not upgraded since currently installed version is compatible with packages

### Screenshots

**Pattern A**
<img width="468" alt="image" src="https://github.com/vrchat-community/creator-companion/assets/22656849/ab67b8a2-7bcd-4fba-b1a4-617d567befe0">

<img width="482" alt="image" src="https://github.com/vrchat-community/creator-companion/assets/22656849/10dc4cb3-0aec-43f8-9f3b-abe1bbfd2b6e">

<img width="451" alt="image" src="https://github.com/vrchat-community/creator-companion/assets/22656849/6431bcf4-3d89-4d59-b1c7-33f2928dbebe">

<img width="471" alt="image" src="https://github.com/vrchat-community/creator-companion/assets/22656849/48b9ab4f-0f15-4f99-ace7-f31bb454dc72">

**Pattern B**

<img width="450" alt="image" src="https://github.com/vrchat-community/creator-companion/assets/22656849/843da2fb-de99-4638-a0de-1ac53baf8e30">

<img width="468" alt="image" src="https://github.com/vrchat-community/creator-companion/assets/22656849/730c8ece-f4d8-4815-bbbf-2b3a6001a926">

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.3 and 2.1.4

### OS

Windows 10

### Additional context

I thought this issue is combination of #349 and #350 but still not resolved.

**Comment by anatawa12** [comment] 2023-10-03 04:03
@momo-the-monster Sorry for pinging again. Is this issue under consideration? I think this must be fixed before Worlds 3.4.0 stable release.

**Comment by anatawa12** [comment] 2023-10-06 03:05
@momo-the-monster Sorry for pinging again and again. I think this VCC bug will break project with GUID duplication.

**Comment by momo-the-monster** [comment] 2023-10-06 04:27
@anatawa12 we have a fix and we are working on testing it and getting it to release as soon as we can, thank you.

**Comment by Sayamame-beans** [comment] 2023-10-09 08:12
I am very confused, but Pattern B seems to reproduce even when updating the SDK manually. This means,
1. Create project with VRCSDK 3.3.0 and UdonSharp.
2. Install package depends on UdonSharp.
3. Update VRCSDK to 3.4.0 manually.
4. UdonSharp is not removed.

It is an unbelievably fatal problem that legacyPackages does not work even though other packages that depend on UdonSharp just exist and the SDK was simply updated manually (with little influence from other vpmDependencies, etc.).
I assure you that this is the cause of the problem that is currently troubling many users.

**Comment by momo-the-monster** [comment] 2023-10-13 22:16
Should be fixed now in [Creator Companion 2.1.5](https://vcc.docs.vrchat.com/news/release-2.1.5), thanks for reporting!

**Closed by momo-the-monster** 2023-10-13 22:16 UTC
Labels: bug
