### ISSUE TITLE
Package reinitialization

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/creator-companion#150] opened 2023-03-15 22:12 UTC
Add a button to reinitialize packages, in case a user would like to reset them.

Currently, if a user accidentally deletes or modifies a package, the VCC doesn't allow them to fix it. They'd have to go into their packages folder, delete the package, and let it be fully reimported.

It'd be nice to allow users to delete a package's folder directly in the VCC's UI.

Let it be known that orels  has objections, which is fair.

Fax Comment: Our public instructions for resetting the SDK are outdated https://help.vrchat.com/hc/en-us/articles/360062658873-I-m-getting-errors-after-importing-the-VRCSDK-I-don-t-see-menu-options-in-the-VRCSDK

(Thank you to One One for bringing this up)

What would our current instructions be? Should we make this a documentation task?

**Comment by anatawa12** [comment] 2023-03-16 12:04
Duplicate of #39?

**Closed** 2023-03-29 23:30 UTC
Labels: duplicate, UI/UX
