### ISSUE TITLE
[BUG] Wrong project path, cannot be changed forever

### ISSUE THREAD

**Issue by Tsut-ps** [vrchat-community/creator-companion#330] opened 2023-07-27 14:05 UTC
### Describe the bug

I hit a bug in which I inadvertently specified an impossible location such as "This PC" instead of "C:\xxxx\" in the VCC project path, which resulted in an "No valid path selected" message forever, and I could not even change folders.

### To Reproduce

1. Open VCC.

1. Select "Create New Project".

1. Specify an invalid path in "Pick New Folder" on the right side of "Project Location". For example, "This PC".

1. If you select "This PC", the Project Location will be changed to "::{20D04FE0-3AEA-1069-A2D8-08002B30309D}" on its own (probably because it is an unexpected path).

1. It cannot be changed from "Pick New Folder". When clicking on it, ONLY "No valid path selected" is displayed.

### Expected behavior

I want it to be like this
- The path is wrong, it throws an error.
- It is possible to specify this path again after specifying it.

### Screenshots

![image](https://github.com/vrchat-community/creator-companion/assets/73014392/465ad5fe-235c-41c7-8bd3-144d3fb9bbc1)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.2

### OS

Windows 11

### Additional context

By modifying the "defaultProjectPath" in ` C:\Users\<userName>\AppData\Local\VRChatCreatorCompanion\settings.json `, the project path can be set back to correct.

Translated with DeepL (JP→EN)

**Comment by Faxmashine** [comment] 2023-07-31 13:37
Hi @Tsut-ps ! Thank you for reporting this issue. We'll look into fixing it.

In the meantime, the workaround you provided is correct. The error is caused by an incorrect value in `settings.json`.

1. Close the VCC.
2. Go to `%LocalAppData%/VRChatCreatorCompanion`
3. Open `settings.json`
4. Remove the line that contains `"defaultProjectPath": ...`, or replace the broken path with a valid path.

**Comment by Loomis2** [comment] 2023-08-29 23:13
im having this exact issue, but i cant find the files to delete.

**Comment by momo-the-monster** [comment] 2023-09-27 19:31
Fixed in [VCC 2.1.4](https://vcc.docs.vrchat.com/news/release-2.1.4).

**Closed by momo-the-monster** 2023-09-27 19:31 UTC
Labels: bug

**Comment by Loomis2** [comment] 2023-09-27 19:36
i’ll check if it’s fixed but last i recall it is not.
