### ISSUE TITLE
[FEATURE] [VCC-WEB] Ability to launch a new project targeting Android

### ISSUE THREAD

**Issue by hyblocker** [vrchat-community/creator-companion#94] opened 2023-02-23 10:18 UTC
**The ability to set a project to target Android over Windows when creating a new project through VCC.**

In the page which allows a user to select a template and create a project, a toggle should be available to allow a user to immediately create a project which is targeting Android, which is for people who only or primarily target the Quest.
This is better for that subset of users as they typically end up having to make a new project (targeting DX11 on Windows), waiting for Unity to import every asset, manually change the build target to Android, and then wait for Unity to re-import all assets again.

**Comment by Faxmashine** [comment] 2023-03-28 21:19
Duplicate of https://github.com/vrchat-community/creator-companion/issues/35

**Closed by Faxmashine** 2023-03-28 21:19 UTC
Labels: duplicate, enhancement, vcc-web
