### ISSUE TITLE
[FEATURE] Sorting recently open Projectes!

### ISSUE THREAD

**Issue by FurrySKY420** [vrchat-community/creator-companion#234] opened 2023-04-07 05:13 UTC
**Is your feature request related to a problem? Please describe.**
rn, when you open a Project is not sorted at the top of the list is Sorted by when you added it to your CCV Tool

**Describe the solution you'd like**
I would like when VRC would add a Sorting System like "Sorted by recently open" (recently open would be sorted at the top of the list)

**Describe alternatives you've considered**
There is no alternatives in my Head

**Additional context**
Here a Scrrenshot: [https://i.imgur.com/vu2PsFe.png](url)
![download (2)](https://user-images.githubusercontent.com/37195796/230545358-dbe6f9c7-bf49-401d-b6fe-3bf16010e404.png)

**Comment by anatawa12** [comment] 2023-04-07 11:21
Is this duplicate of #68?

**Comment by anatawa12** [comment] 2023-05-05 11:10
Might be fixed by #248?

**Closed** 2023-05-16 18:07 UTC
