### ISSUE TITLE
[BUG] Issue when Migrating Project

### ISSUE THREAD

**Issue by PhoxVRC** [vrchat-community/creator-companion#12] opened 2022-10-19 08:52 UTC
**Describe the bug**
When migrating a project it doesnt advance past "Deleting Assets\VRCSDK and folders it contains
**To Reproduce**
1. Click on projects
2. Find a old project
3. Click migrate
4. Choose Migrate in Place

**Expected behavior**
It properly migrates and finishes.

**Screenshots**
![image](https://user-images.githubusercontent.com/42518848/196643209-d00c15de-d37a-4458-b87a-6c050d207c6b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H2

**Additional context**

**Comment by PhoxVRC** [comment] 2022-10-22 15:53
If I Manually delete the VRCSDK contents then restart the migration it completes.

**Comment by momo-the-monster** [comment] 2022-11-09 23:02
@PhoxVRC - sorry to see you're having this issue. However, we have a suite of projects that we test-migrate as part of each release, and we have not come across this issue. Can you provide any more information on how to reproduce this issue?

**Comment by momo-the-monster** [comment] 2022-11-17 21:49
Closing due to lack of follow-up information, please reopen if you can provide additional details, thanks!

**Closed by momo-the-monster** 2022-11-17 21:49 UTC
Labels: no repro
