### ISSUE TITLE
[FEATURE] Add an Icon to show that there are available package updates

### ISSUE THREAD

**Issue by ShaunDreclin** [vrchat-community/creator-companion#472] opened 2024-05-02 07:53 UTC
Right now the only way to keep a project updated is to remember to click "Manage Project" and check for package updates regularly, this leads to packages frequently being out of date. Some sort of icon in the project list would be very helpful.

**Comment by orels1** [comment] 2024-05-02 12:04
While I do not have anything to share at this time - we are aware that a lot of people want this feature.

I will close this issue as it is a duplicate of https://github.com/vrchat-community/creator-companion/issues/66

**Closed by orels1** 2024-05-02 12:04 UTC
Labels: enhancement
