### ISSUE TITLE
[FEATURE] Easy project renaming 

### ISSUE THREAD

**Issue by PeetyPT** [vrchat-community/creator-companion#470] opened 2024-05-01 11:14 UTC
Currently if you want to rename a project, you need to go into the file location to rename it and then manually add it back into VCC

I want users to be able to rename projects through VCC

**Comment by anatawa12** [comment] 2024-05-01 11:15
Duplicate of #78?

**Comment by PeetyPT** [comment] 2024-05-01 11:19
Yeah I see that #78 is the same, I'll close this one

**Closed** 2024-05-01 11:20 UTC
Labels: enhancement
