### ISSUE TITLE
[BUG] Udon broken in the SDK.

### ISSUE THREAD

**Issue by Krahazik** [vrchat-community/creator-companion#217] opened 2023-03-22 21:35 UTC
**Describe the bug in detail:**
A clear description of what the bug is.
With a brand new project created from the VRChat Creator Companion, getting lots of errors in the Unity editor related to Udon. None of the Udon examples are functional. All have the same error related to missing source script. No ability to create new Udon scripts or edit existing scripts.

**Provide steps/code to reproduce the bug:**
Steps or code to reproduce the behavior.
- Open the CreatorCompanion application.
- Create a new world project.
- Open the new project with Unity.
- Attempt to edit any of the example Udon scripts.
- Attempt to create a new Udon script.

**Expected behavior:**
What was the excepted result?
Fewer errors or no errors related to Udon when opening the project.
Access to the graph editor when selecting any Udon script to edit.

**Additional Information:**
Provide any additional information here.
Using Unity Editor 2019.4.31f1 Personal

Attempting to examine one of the example scripts, notice the error on the right in the Inspector Panel.
![VRC Editor Udon Fail 230322A](https://user-images.githubusercontent.com/97745982/227041693-220abe59-8444-419a-91f0-05fd53286bd6.jpg)

List of errors that appear when loading the project.
![VRC Editor Udon Fail 230322B](https://user-images.githubusercontent.com/97745982/227042209-43c8dc9b-c1a7-41c1-b683-cdb7e70b86ca.jpg)

**Comment by anatawa12** [comment] 2023-03-26 06:24
Can you show me all errors on the Unity? It may help me with resolving this issue and may help VRChat official to fix this issue if it's a bug.

**Comment by momo-the-monster** [comment] 2023-04-13 19:07
Closing due to lack of updates and inability to reproduce.

**Closed by momo-the-monster** 2023-04-13 19:07 UTC
Labels: question, no repro
