### ISSUE TITLE
[BUG]Failed to update the path to Unity: null

### ISSUE THREAD

**Issue by alwayslate233** [vrchat-community/creator-companion#300] opened 2023-05-23 15:36 UTC
### Describe the bug

I installed unity hub and the exact version of unity that building a vrchat project needs, but when I put the path of unity.exe in Creator Companion, the error message pops up saying _Failed to update the path to Unity: null_. 
I had no idea why it happens or what I could do. The only information I found about this was another thread here, but it was closed before any further discussion happens. 

### To Reproduce

1. Start CreatorCompanion
2. As the message shows up which says _Path to a Unity Editor is not set, you will be unable to open projects._, click _fix now_
3. Click I already have Unity
4. Find unity.exe in the folder as it requests
5. Get the error message

### Expected behavior

The installation was supposed to go well and the path should be recognized, as almost no one else was trying to discuss about this error on the internet. 

### Screenshots

![无标题](https://github.com/vrchat-community/creator-companion/assets/44921965/09c225ec-9c6a-45ef-abcb-abdbdd098b77)
The error message comes in the bottom. 

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.1

### OS

Windows 10

### Additional context

Edited: It seems that I was using the unity version specifically offered for China, which was not compatible in CreatorCompanion. I don't know if this still counts as a bug or not, so I'll leave it here open for now. Case closed if further development on such compatibility is not planned.

**Comment by anatawa12** [comment] 2023-05-25 05:06
It seem like a duplicate of #152.

**Comment by momo-the-monster** [comment] 2023-06-02 22:52
Closed to merge issue with #305.

**Closed by momo-the-monster** 2023-06-02 22:52 UTC
Labels: bug
