### ISSUE TITLE
[FEATURE] Make it clearer when there is an update for a package or add an "update" button on the main page

### ISSUE THREAD

**Issue by Ikbenmathijs** [vrchat-community/creator-companion#116] opened 2023-03-09 19:51 UTC
**Is your feature request related to a problem? Please describe.**
In the old unity based creator companion, you'd have to click on a project before you can actually open it, so you can see the big green "update" button on all your packages *before* you open the project. Now there's a direct "open project" button which is really nice, but it might lead to people not updating their packages because they have to press "manage project" first, which not everyone will do every time

**Describe the solution you'd like**
Either an indicator on the projects page indicating there is an update for a package, or even better, a direct "update all packages" button next to the open project button
(something like [this](https://cdn.discordapp.com/attachments/554234775590666251/1083477025525866626/image.png))

**Comment by DrBlackRat** [comment] 2023-03-09 20:31
Duplicate of #66

**Comment by orels1** [comment] 2023-03-09 20:41
As mentioned above - this was already proposed, you can go upvote the #66 using the reactions

**Closed by orels1** 2023-03-09 20:41 UTC
