### ISSUE TITLE
[BUG] Inability to upload avatars using the companion

### ISSUE THREAD

**Issue by EnnaelK3219** [vrchat-community/creator-companion#11] opened 2022-10-09 13:32 UTC
**Describe the bug**
Inability to upload avatars using the companion

**To Reproduce**

1. Load up Creator Companion
2. Load avatar
3. Modify avatar to specifications
4. Log into VRChat SDK if not already logged in
5. Look at upload requirements and see that it's all met, yet the upload button and test button are still greyed out

**Expected behavior**
Expected Behavior is that any avatar should be able to be uploaded with or without modifications during step 3.

**Screenshots**

**Desktop (please complete the following information):**
Desktop, whichever version was first uploaded to the site

**Additional context**
No additional context.  It just won't allow uploads.  The same SDK used outside creator companion ALSO doesn't allow uploading, so it's an SDK problem.

**Comment by momo-the-monster** [comment] 2022-11-09 23:00
https://user-images.githubusercontent.com/737888/200960230-972f8c07-0c27-4883-b272-ce8b21e04065.mp4

This does not appear to be the case as of VCC 1.0.3 and SDK 3.1.10, as you can see in the video above (edited for privacy and efficiency). Can you provide exact steps to reproduce the issue?

**Comment by momo-the-monster** [comment] 2022-11-17 21:50
Closing due to lack of follow-up information, please reopen if you can provide additional details, thanks!

**Closed by momo-the-monster** 2022-11-17 21:50 UTC
Labels: no repro
