### ISSUE TITLE
Sort projects by last opened in settings

### ISSUE THREAD

**Issue by KhopeshActual** [vrchat-community/creator-companion#248] opened 2023-04-13 19:14 UTC

**Comment by anatawa12** [comment] 2023-04-14 18:33
Looks lile a duplicate of #68.

**Comment by orels1** [comment] 2023-04-15 00:51
@anatawa12 #68 is a larger feature request for better project organisation, which we still want to do, but its a bit of a larger scope than simply sorting by last opened by default.

**Closed** 2023-05-04 23:10 UTC
Labels: enhancement
