### ISSUE TITLE
[BUG] Remove "Editor version at ...\2023.1.19f1\Editor\Unity.exe is not supported" message and toast, people aren't only VRChat content creators

### ISSUE THREAD

**Issue by hai-vr** [vrchat-community/creator-companion#380] opened 2023-11-17 04:59 UTC
### Describe the bug

The message "[INF] Editor version at C:\Program Files\Unity\Hub\Editor\2023.1.19f1\Editor\Unity.exe is not supported" shows up as an error.

Remove this message and toast.

VRChat content isn't the only reason people have the Unity Editor installed.

### To Reproduce

- Have any version of Unity Editor 2021, 2022, or 2023 installed.
- Click on Settings
- Wait

### Expected behavior

No error toast shows up

### Screenshots

![image](https://github.com/vrchat-community/creator-companion/assets/60819407/a8bc3962-4ce7-4c2a-83c0-186f93de5401)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.6

### OS

Windows 10

**Comment by anatawa12** [comment] 2023-11-17 05:08
Is this same as #362?

**Comment by orels1** [comment] 2023-11-18 20:51
The frontend, currently, treats every message (including Information like the above) the same. We do want to adjust that so, by default, only severe logs are shown in that popup, and the rest is just in the logs tab. That would address this issue and many other similar logs that might be treated as errors, when its just information mainly for debug/support purposes.

I'll close this as a duplicate of #352

**Closed by orels1** 2023-11-18 20:51 UTC
Labels: bug
