### ISSUE TITLE
[BUG] Avatar SDK may be imported in World Projects through the "Manage Package" window.

### ISSUE THREAD

**Issue by BlackStartx** [vrchat-community/creator-companion#216] opened 2023-03-22 01:10 UTC
**Describe the bug**
Packages that depends on the "VRChat SDK - Avatar" are not filtered out on World projects "Manage Package" window correctly, causing the Avatar SDK being imported in a World project if those packages are installed.

This will also cause issues and troubles on world publishing.

**To Reproduce**
1. Open the VCC app.
2. Create a new "World" project (or select one)
3. Locate the Gesture Manager in the "Manage Package" tab and instal it.
4. Wait and then open the project.
5. The "Build And Publish" button does not work anymore.

**Expected behavior**
Packages that depends on the Avatar SDK should not be visualized or imported in a World project, and viceversa.

**Screenshots**
Example on latest VCC app:

![image](https://user-images.githubusercontent.com/26898122/226772236-ded2bec9-b811-4dfb-8bcf-4f760eead50e.png)

The project after importing Gesture Manager 3.8.2:

![image](https://user-images.githubusercontent.com/26898122/226772376-b576edde-ddb9-499d-a4ef-f320c414ba44.png)

This issue was **NOT** present on version 1.0.6 of VCC:

![image](https://user-images.githubusercontent.com/26898122/226772049-813cea19-82dc-4ed1-91b3-61cd5defa102.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Additional context**
As I said on Discord:

> I think the reason my tool appears in a world project list (while other avatar tools doesn't) is because the initial release of my tool as a curated package (Gesture Manager 3.8.0) didn't include the "VRChat SDK - Avatar" as a dependency.
> 
> This was actually intentional since my tool does works fine and does not throw errors if there are no VRChat SDKs in the project, but 
I was not aware of the fact that dependency also works as a filter for the VCC Package window.
> 
> This resulted in the "VRChat SDK - Avatar" being added as a dependency in 3.8.1, while the 3.8.0 version remains untouched~

This issue may also be fixed by adding the Avatar SDK dependency on my first release, causing it to be filtered out from the World "Manage Package" window.
(Which I agree should also be done, since it makes no sense for it to be listed in a world package window)

Thanks and sorry for the issue,
- BlackStartx

**Comment by anatawa12** [comment] 2023-03-22 05:00
Maybe duplicate of #199?

**Comment by BlackStartx** [comment] 2023-03-22 13:20
Welp, that does sound like the same issue~

Shall I close this or morph it focusing on adding the "VRChat SDK - Avatar" dependency on the initial release of the Gesture Manager so it fixes just this edge-case but also removes it from the World package window?
###### Since it kinda looks out of place there.

**Comment by Faxmashine** [comment] 2023-06-14 16:06
Thank you for your report!

This issue is specific to Gesture Manager. It _technically_ supported Worlds and Avatars (on release), which caused issues occasionally.

@BlackStartx, would removing the Avatars SDK dependency from the initial release be an acceptable solution?

If not, we can look into alternate solutions within the VCC itself.

**Comment by Faxmashine** [comment] 2023-06-14 19:02
Well, that's wonderful to hear! Thank you so much for taking the time to fix your package.

Have a great week.

**Closed by Faxmashine** 2023-06-14 19:02 UTC
Labels: bug, vcc-web
