### ISSUE TITLE
[FEATURE] Update all packages button

### ISSUE THREAD

**Issue by ImDragonxd07** [vrchat-community/creator-companion#536] opened 2024-09-24 19:55 UTC
When i haven't updated an avatar in a while, I like to update all of my packages to the latest ones. This takes forever when it only lets you do one at a time. A feature to update all packages would make this much faster.

**Comment by anatawa12** [comment] 2024-10-03 15:40
duplicate of #172

**Comment by orels1** [comment] 2024-10-08 14:14
As mentioned above - a duplicate of #172

**Closed** 2024-10-08 14:14 UTC
Labels: enhancement
