### ISSUE TITLE
[BUG]  Symblink be not working

### ISSUE THREAD

**Issue by slord399** [vrchat-community/creator-companion#396] opened 2023-12-12 04:50 UTC
### Describe the bug

Unity Hub Installation button and Docoment link seems no longer works.
![Aa0SV5i](https://github.com/vrchat-community/creator-companion/assets/50810875/4d4b626a-e06d-4d7a-8829-09e54eeb21e7)

### To Reproduce

1. Go to VCC
2. Go to section shown in pic
3. Click on button

### Expected behavior

Open approciate Unity Installation screen or Document page.

### Screenshots

![Aa0SV5i](https://github.com/vrchat-community/creator-companion/assets/50810875/ef41c913-a162-4942-bc81-9f75bc766993)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.2

### OS

Windows 10

**Comment by anatawa12** [comment] 2023-12-12 04:51
Duplicate of #384?

**Closed** 2023-12-12 04:53 UTC
Labels: bug
