### ISSUE TITLE
[FEATURE] [VCC-WEB] Add proper Sorting Options in the Projects List

### ISSUE THREAD

**Issue by BluWizard10** [vrchat-community/creator-companion#120] opened 2023-03-10 02:46 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the list of Projects are sorted based on how recent it was added. This is quite annoying as someone who is obsessed with organization.

**Describe the solution you'd like**
It would be great if you guys can add sorting options in a way that is better than Unity Hub. Like, for say, Worlds, Avatars, Alphabetical, and (in my option what I want), sort by Recently Opened like how it does in Unity Hub.

**Additional Context**
Sorting Options is a necessity in our daily lives. It's annoying that Windows File Explorer does that so much better than Creator Companion.

**Comment by DrBlackRat** [comment] 2023-03-10 07:28
Duplicate of #68

**Comment by BluWizard10** [comment] 2023-03-10 08:06
> Duplicate of #68 

Thanks, thought I never saw it.

**Closed** 2023-03-10 08:06 UTC
