### ISSUE TITLE
[BUG] [VCC-WEB] Projects page scroll bar results in misalignment of the "Project Type" header

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#115] opened 2023-03-09 16:10 UTC
**Issue:**  
When you change the window height of the VCC while having the Projects Page open a scroll bar appears once you make it to small to display all of the Projects (List View).

This scroll bar appearing initially results in the `Project Type` header getting out of alignment, though when you make it even smaller it gets back into alignment.

**Expected Behaviour:**
The `Project Type` header  should stay in alignment no matter what.

**Attachments:**  
Here is a video showcasing the issue:

https://user-images.githubusercontent.com/46327609/224083812-ecb96e9e-7384-4149-8e3d-8d69d414021b.mp4

**Comment by orels1** [comment] 2023-03-09 16:30
Note for the future bugfix:
This is caused by the height calculation not taking into the account the header height, and offsetting the headers a bit later than when the scrollbar is supposed to apepar

**Comment by orels1** [comment] 2023-03-10 23:38
Should be fixed in v2.0.1

**Closed by orels1** 2023-03-10 23:38 UTC
Labels: bug, vcc-web
