### ISSUE TITLE
[FEATURE] Add check and warning if someone place the project map inside VCC program map.

### ISSUE THREAD

**Issue by MrDummyNL** [vrchat-community/creator-companion#228] opened 2023-04-01 16:42 UTC
**Is your feature request related to a problem? Please describe.**
Someone found out it can damage your project map. Because updating VCC seems change inside program map, can erase even project map. Thank to DarrenZeus pointing out this problem.
See: https://twitter.com/DarrenZeusVR/status/1641881687322775563

**Describe the solution you'd like**
VCC need extra internal checks to warn the user don't put project map inside VCC map. Otherwise they will have risk to lose data.

**Describe alternatives you've considered**
There is no alternative. It needs internal check to warn user to ensure project data is not lost.

**Additional context**
This must done asap, because some users might put project map inside VCC map, and there is risk confirmed. Should not wait too long to add function to check if user didn't put project map inside VCC map.

**Comment by anatawa12** [comment] 2023-04-01 16:49
I think duplicate of #40, isn't it?

**Comment by orels1** [comment] 2024-02-22 17:23
As mentioned by anatawa12 above - VCC warns when you try to create a project inside VCC's installation folder.
The installer also no longer removes all the files before updates

**Closed by orels1** 2024-02-22 17:23 UTC
